/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author nvettera
 */
public class Print extends javax.swing.JPanel {
	Panel p;
    /**
     * Creates new form Print
     */
    public Print(Panel p) {
        this.p=p;
    	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        printBtnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        printLeistungsuebersichtRadio = new javax.swing.JRadioButton();
        printStudienbescheinigungRadio = new javax.swing.JRadioButton();
        printStundenplanRadio = new javax.swing.JRadioButton();
        printStudienverlaufsbescheinigungRadio = new javax.swing.JRadioButton();
        printBtn = new javax.swing.JButton();

        jLabel1.setText("Druckmenü:");

        printLeistungsuebersichtRadio.setText("Leistungsübersicht drucken");

        printStudienbescheinigungRadio.setText("Studienbescheinigung drucken");

        printStundenplanRadio.setText("Stundenplan drucken");

        printStudienverlaufsbescheinigungRadio.setText("Studienverlaufsbescheinigung drucken");

        printBtn.setText("Drucken");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(printLeistungsuebersichtRadio)
                    .addComponent(printStudienbescheinigungRadio)
                    .addComponent(printStundenplanRadio)
                    .addComponent(printStudienverlaufsbescheinigungRadio)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(printBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(printLeistungsuebersichtRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printStudienbescheinigungRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printStundenplanRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printStudienverlaufsbescheinigungRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printBtn)
                .addContainerGap(265, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
    	if (printLeistungsuebersichtRadio.isSelected()==true)p.frame.getController().print(1);
    	else if (printStudienbescheinigungRadio.isSelected()==true)p.frame.getController().print(2);
    	else if (printStundenplanRadio.isSelected()==true)p.frame.getController().print(3);
    	else if (printStudienverlaufsbescheinigungRadio.isSelected()==true)p.frame.getController().print(4);
    }//GEN-LAST:event_printBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton printBtn;
    private javax.swing.ButtonGroup printBtnGroup;
    private javax.swing.JRadioButton printLeistungsuebersichtRadio;
    private javax.swing.JRadioButton printStudienbescheinigungRadio;
    private javax.swing.JRadioButton printStudienverlaufsbescheinigungRadio;
    private javax.swing.JRadioButton printStundenplanRadio;
    // End of variables declaration//GEN-END:variables
}
