/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author nvettera
 */
public class VorlDetailPanel extends javax.swing.JPanel {
    private int id;
    String select;
    Panel p;
    /**
     * Creates new form VorlDetailPanel
     */
    public VorlDetailPanel(Panel p,int id,String select) {
    	this.p=p;
    	this.select=select;
        this.id=id;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titelLabel = new javax.swing.JLabel();
        detailLabel = new javax.swing.JLabel();
        lehrenderLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        pruefenderLabel = new javax.swing.JLabel();
        anOabBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 500));

        titelLabel.setText("Vorlesungstitel:");

        detailLabel.setText("Beschreibung:");

        lehrenderLabel.setText("Lehrenden:");

        timeLabel.setText("Zeit:");

        pruefenderLabel.setText("Prüfender:");

        anOabBtn.setText("Von dieser Vorlesung abmelden");
        switch(id){
            case 0:anOabBtn.setVisible(false);break;
            case 1:anOabBtn.setText("Zu dieser Vorlesung anmelden");break;
            default:break;
        }
        anOabBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anOabBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titelLabel)
                    .addComponent(detailLabel)
                    .addComponent(lehrenderLabel)
                    .addComponent(timeLabel)
                    .addComponent(pruefenderLabel)
                    .addComponent(anOabBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(455, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lehrenderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pruefenderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anOabBtn)
                .addContainerGap(320, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void anOabBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anOabBtnActionPerformed
       if (anOabBtn.getText().equals("Zu dieser Vorlesung anmelden"))
            anOabBtn.setText("Von dieser Vorlesung abmelden");
       else anOabBtn.setText("Zu dieser Vorlesung anmelden");
       p.frame.getController().anmelden(select);
    }//GEN-LAST:event_anOabBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anOabBtn;
    private javax.swing.JLabel detailLabel;
    private javax.swing.JLabel lehrenderLabel;
    private javax.swing.JLabel pruefenderLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel titelLabel;
    // End of variables declaration//GEN-END:variables
}
